create database rank_up;

\c rank_up;

create table users
(
    chat_id       bigint not null,
    user_id       bigint not null,
    experience    bigint,
    first_name    varchar(255),
    language_code varchar(255),
    last_name     varchar(255),
    rank_level    integer,
    registered_at timestamp(6),
    user_name     varchar(255),
    primary key (chat_id, user_id)
);

create table chats
(
    id    bigint not null
        primary key,
    date  integer,
    title varchar(255)
);

create table images
(
    image_url varchar(255) not null
        primary key
);

create table ranks
(
    level            integer generated by default as identity
        primary key,
    experience       bigint,
    level_up_message varchar(255),
    name             varchar(255)
);

create table default_ranks
(
    level      integer not null
        primary key,
    experience bigint,
    name       varchar(255)
);

INSERT INTO default_ranks (level, experience, name)
VALUES
    (1, 20, 'Novice'),
    (2, 50, 'Learner'),
    (3, 90, 'Explorer'),
    (4, 140, 'Activist'),
    (5, 200, 'Adept'),
    (6, 270, 'Master'),
    (7, 350, 'Expert'),
    (8, 440, 'Professional'),
    (9, 540, 'Veteran'),
    (10, 650, 'Sage'),
    (11, 770, 'Elite'),
    (12, 900, 'Legend'),
    (13, 1040, 'Guru'),
    (14, 1190, 'Inspirer'),
    (15, 1350, 'Patriarch'),
    (16, 1520, 'Titan'),
    (17, 1700, 'Overlord'),
    (18, 1890, 'Ideal'),
    (19, 2090, 'Mythical Hero'),
    (20, 2300, 'Immortal');